### PR TITLE
Change vagrant box to ubuntu/trusty64. Fixes #8.

### LINKED ISSUE #8: Switch Vagrantfile to ubuntu/trusty64
Currently using hashicorp/precise64, which is deprecated.

### PR DESCRIPTION
**Pull request by briangreenery**

### CODE REVIEW

**Comment by ottumm** [comment]
Does 

```
vagrant up
vagrant ssh
npm install
npm test
```

still succeed?

**Comment by ottumm** [comment]
Also, @amcgee, what OS are we using in production? We should keep the vagrant box in sync with that.

**Comment by ottumm** [comment]
Also, also (sorry @briangreenery), I'm thinking of switching vagrant to use the docker image that I'm working on building in https://github.com/ottumm/strato2/commits/docker. That way `vagrant up` will be faster and it will always be in sync with production.

Juuust fyi. I think it's probably still fine to update to trusty64 now though.

**Comment by briangreenery** [comment]
Yeah, that still works.

It'd be super cool if the tests could run outside of the vm also.

**Comment by ottumm** [comment]
It would, yes. The tests depend on MongoDB. If you have that running locally and listening on 27017 then `npm test` should succeed.

**Comment by ottumm** [comment]
:+1: from me.

**Comment by amcgee** [comment]
We could probably forward the MongoDB port from Vagrant, then you could do something like this (abbreviated): `vagrant up; DATABASE_URL=localhost:27117 npm test`

**Comment by ottumm** [comment]
Actually, yeah, we already forward the MongoDB port (27117) from Vagrant, so you can do exactly as @amcgee described.

**Comment by briangreenery** [comment]
I guess I was more thinking that the tests could be more unit tests, and then mongo could be mocked instead of using the real mongo. I don't think we have to go that far though.

**Comment by amcgee** [comment]
Production is currently Ubuntu 14.04 x64 running Dokku,  Good change.

I like the idea of mocking Mongo eventually, but it's not critical path currently.

**Pull request merged**
